python python/analyzer.py -m MultiAlkEm -a eff -s HV12 -cfg cfg/treshold_5s.txt -n HVScan12_MultiAlkEm
python python/analyzer.py -m GaAsEm -a eff -s HV12 -cfg cfg/treshold_5s.txt -n HVScan12_GaAsEm
python python/analyzer.py -m Double9040 -a eff -s HV12 -cfg cfg/treshold_5s.txt -n HVScan12_Double9040
python python/analyzer.py -m Double9090 -a eff -s HV12 -cfg cfg/treshold_5s.txt -n HVScan12_Double9090
python python/analyzer.py -m MultiAlkEm -a eff -s HV1 -cfg cfg/treshold_5s.txt -n HVScan1_MultiAlkEm
python python/analyzer.py -m GaAsEm -a eff -s HV1 -cfg cfg/treshold_5s.txt -n HVScan1_GaAsEm
python python/analyzer.py -m Double9040 -a eff -s HV1 -cfg cfg/treshold_5s.txt -n HVScan1_Double9040
python python/analyzer.py -m Double9090 -a eff -s HV1 -cfg cfg/treshold_5s.txt -n HVScan1_Double9090
python python/analyzer.py -m Double9040 -a eff -s HV2 -cfg cfg/treshold_5s.txt -n HVScan2_Double9040
python python/analyzer.py -m Double9090 -a eff -s HV2 -cfg cfg/treshold_5s.txt -n HVScan2_Double9090

python python/analyzer.py -m MultiAlkEm -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan12_MultiAlkEm
python python/analyzer.py -m GaAsEm -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan12_GaAsEm
python python/analyzer.py -m Double9040 -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan12_Double9040
python python/analyzer.py -m Double9090 -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan12_Double9090
python python/analyzer.py -m MultiAlkEm -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan1_MultiAlkEm
python python/analyzer.py -m GaAsEm -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan1_GaAsEm
python python/analyzer.py -m Double9040 -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan1_Double9040
python python/analyzer.py -m Double9090 -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan1_Double9090
python python/analyzer.py -m Double9040 -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan2_Double9040
python python/analyzer.py -m Double9090 -a eff -s X0 -cfg cfg/treshold_5s.txt -n X0Scan2_Double9090