python python/analyzer.py -cfg cfg/treshold_5s.txt -m Double9090 -a eff -n HVScan1_double -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m Double9040 -a eff -n HVScan1_double -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m GaAsEm -a eff -n HVScan1_emitter -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m MultiAlkEm -a eff -n HVScan1_emitter -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m Double9090 -a eff -n HVScan2_double -s HV1
python python/analyzer.py -cfg cfg/treshold_5s.txt -m Double9040 -a eff -n HVScan2_double -s HV1
python python/analyzer.py -cfg cfg/treshold_5s.txt -m GaAsEm -a eff -n HVScan2_emitter -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m MultiAlkEm -a eff -n HVScan2_emitter -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m GaAsEm -a eff -n HVScan2b_emitter -s HV12
python python/analyzer.py -cfg cfg/treshold_5s.txt -m MultiAlkEm -a eff -n HVScan2b_emitter -s HV12
